
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp_container
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://db:27017/mydatabase
    command: flask run --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: myapp_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

