services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp_container
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: myapp_mongodb
    environment:
    - MONGO_INITDB_DATABASE=test_mongodb
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

